# Experiment 9
## NumPy – Array and Matrix Operations

Activity 1 – Create NumPy Array

In [4]:
import sys
print(sys.executable)

c:\Users\HP\Python\.venv\Scripts\python.exe


In [7]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print("Array:", arr)
print("Type:", type(arr))

Array: [10 20 30 40 50]
Type: <class 'numpy.ndarray'>


Activity 2 – Create 2D Array (Matrix)

In [8]:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Matrix:")
print(matrix)

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Activity 3 – Array Shape and Size

In [9]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])

print("Array:")
print(arr)

print("Shape:", arr.shape)
print("Size:", arr.size)
print("Dimensions:", arr.ndim)

Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Size: 6
Dimensions: 2


Activity 4 – Zeros and Ones Array

In [10]:
import numpy as np

zeros = np.zeros((3,3))
ones = np.ones((2,4))

print("Zeros Array:")
print(zeros)

print("Ones Array:")
print(ones)

Zeros Array:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Activity 5 – Arithmetic Operations on Arrays

In [11]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


Activity 6 – Matrix Addition

In [12]:
import numpy as np

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

C = A + B

print("Matrix Addition:")
print(C)

Matrix Addition:
[[ 6  8]
 [10 12]]


Activity 7 – Matrix Multiplication

In [13]:
import numpy as np

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

C = np.dot(A, B)

print("Matrix Multiplication:")
print(C)

Matrix Multiplication:
[[19 22]
 [43 50]]


Activity 8 – Transpose of Matrix

In [14]:
import numpy as np

A = np.array([[1,2,3],[4,5,6]])

print("Original Matrix:")
print(A)

print("Transpose:")
print(A.T)

Original Matrix:
[[1 2 3]
 [4 5 6]]
Transpose:
[[1 4]
 [2 5]
 [3 6]]
